info:
  contact: {}
paths:
  /originalurl:
    get:
      consumes:
      - application/json
      description: Retrieves a short URL if it exists, or creates a new one if it
        does not.
      parameters:
      - description: Original URL
        in: query
        name: originalUrl
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Short URL
          schema:
            type: string
        "400":
          description: Original URL is required
          schema:
            type: string
        "500":
          description: Failed to generate a short URL or Internal Server Error
          schema:
            type: string
      summary: Retrieve or create a short URL
      tags:
      - URLs
  /shorturl:
    get:
      consumes:
      - application/json
      description: Retrieves the original URL from a given short URL.
      parameters:
      - description: Short URL
        in: query
        name: shortUrl
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Original URL
          schema:
            type: string
        "400":
          description: Short URL is required
          schema:
            type: string
        "404":
          description: No such original URL found
          schema:
            type: string
      summary: Retrieve the original URL
      tags:
      - URLs
swagger: "2.0"
