# 构建 Angular 前端
FROM node:18 AS build-frontend
WORKDIR /app
COPY urlShortener/package*.json ./
RUN npm install
COPY urlShortener/ .
RUN npm run build -- --project urlShortener --configuration production

# 使用 Nginx 作为最终镜像
FROM nginx:alpine
COPY --from=build-frontend /app/dist/url-shortener /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]